[general]
import = [
  "tinted-terminal/themes/alacritty/base16-tokyo-night-storm.toml"
]

[window.dimensions]
lines = 30
columns = 120

[font]
size = 14

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[terminal]

[terminal.shell]
program = "pwsh"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
