# attic binary cache (also configured system-wide in nix/nix-settings.nix)
extra-substituters = https://attic.dgb.sh/system
extra-trusted-public-keys = system:E5ubGe/xsSF5nf2gxvZBP4WSVVFWis3lo+3A3HERoxc=
