name: Build all systems

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build all systems
        run: |
           nix build --cores 1 .#packages.x86_64-linux.all-nixos-systems --out-link /tmp/all-nixos-systems-gcroot

