name: Nix

on:
  push:
    branches:
      - master

jobs:
  check-flake:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run checks
      run: nix flake check --all-systems -v
